### ISSUE TITLE
GIMP 2.99.19 error at startup (FC39)

### ISSUE THREAD

**Issue by Bgs4269** [uriesk/gimp-nightly-rpmspec#1]
The message popped up on starting GIMP. No images opened or create yet.

```
GNU Image Manipulation Program version 2.99.19
git-describe: GIMP_2_99_19
Build: 20240506.aff33e2 rev 1 for linux
# C compiler #
Using built-in specs.
COLLECT_GCC=/usr/bin/gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/13/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-redhat-linux
Configured with: ../configure --enable-bootstrap --enable-languages=c,c++,fortran,objc,obj-c++,ada,go,d,m2,lto --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-shared --enable-threads=posix --enable-checking=release --enable-multilib --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-gcc-major-version-only --enable-libstdcxx-backtrace --with-libstdcxx-zoneinfo=/usr/share/zoneinfo --with-linker-hash-style=gnu --enable-plugin --enable-initfini-array --with-isl=/builddir/build/BUILD/gcc-13.2.1-20240316/obj-x86_64-redhat-linux/isl-install --enable-offload-targets=nvptx-none --without-cuda-driver --enable-offload-defaulted --enable-gnu-indirect-function --enable-cet --with-tune=generic --with-arch_32=i686 --build=x86_64-redhat-linux --with-build-config=bootstrap-lto --enable-link-serialization=1
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 13.2.1 20240316 (Red Hat 13.2.1-7) (GCC) 

# Libraries #
using babl version 0.1.108 (compiled against version 0.1.108)
using GEGL version 0.4.48 (compiled against version 0.4.48)
using GLib version 2.78.6 (compiled against version 2.78.3)
using GdkPixbuf version 2.42.10 (compiled against version 2.42.10)
using GTK+ version 3.24.41 (compiled against version 3.24.41)
using Pango version 1.51.0 (compiled against version 1.51.0)
using Fontconfig version 2.14.2 (compiled against version 2.14.2)
using Cairo version 1.18.0 (compiled against version 1.18.0)

```
> GIMP-WARNING: gimp_babl_format_get_with_alpha: unsupported format "HSVA float".

Stack trace:
```

# Stack traces obtained from PID 585781 - Thread 585781 #

[New LWP 585832]
[New LWP 585833]
[New LWP 585835]
[New LWP 585872]
[New LWP 585873]
[New LWP 585874]
[New LWP 585916]
[New LWP 585954]

This GDB supports auto-downloading debuginfo from the following URLs:
  <https://debuginfod.fedoraproject.org/>
Enable debuginfod for this session? (y or [n]) [answered N; input not from terminal]
Debuginfod has been disabled.
To make this setting permanent, add 'set debuginfod enabled off' to .gdbinit.
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
0x00007fdfd41d540a in read () from /lib64/libc.so.6
  Id   Target Id                                           Frame 
* 1    Thread 0x7fdfd2425fc0 (LWP 585781) "gimp-2.99"      0x00007fdfd41d540a in read () from /lib64/libc.so.6
  2    Thread 0x7fdfc46006c0 (LWP 585832) "pool-spawner"   0x00007fdfd41e085d in syscall () from /lib64/libc.so.6
  3    Thread 0x7fdfbbc006c0 (LWP 585833) "gmain"          0x00007fdfd41d4e3d in poll () from /lib64/libc.so.6
  4    Thread 0x7fdfc3c006c0 (LWP 585835) "gdbus"          0x00007fdfd41d4e3d in poll () from /lib64/libc.so.6
  5    Thread 0x7fdfc32006c0 (LWP 585872) "worker"         0x00007fdfd41e085d in syscall () from /lib64/libc.so.6
  6    Thread 0x7fdfc28006c0 (LWP 585873) "worker"         0x00007fdfd41e085d in syscall () from /lib64/libc.so.6
  7    Thread 0x7fdfc1e006c0 (LWP 585874) "worker"         0x00007fdfd41e085d in syscall () from /lib64/libc.so.6
  8    Thread 0x7fdfb34006c0 (LWP 585916) "async"          0x00007fdfd41e085d in syscall () from /lib64/libc.so.6
  9    Thread 0x7fdfb2a006c0 (LWP 585954) "pool-gimp-2.99" 0x00007fdfd41e085d in syscall () from /lib64/libc.so.6
#0  0x00007fdfd41d540a in read () at /lib64/libc.so.6
#1  0x00007fdfd5c223b4 in gimp_stack_trace_print () at /lib64/libgimpbase-3.0.so.0
#2  0x0000563da4ab1f1e in gui_message ()
#3  0x0000563da48ebb5a in gimp_show_message ()
#4  0x0000563da4a6eea2 in gimp_message_log_func ()
#5  0x00007fdfd55e0180 in g_logv () at /lib64/libglib-2.0.so.0
#6  0x00007fdfd55e0463 in g_log () at /lib64/libglib-2.0.so.0
#7  0x00007fdfd5bf5250 in gimp_color_set_alpha () at /lib64/libgimpcolor-3.0.so.0
#8  0x0000563da4890a71 in gimp_context_real_set_foreground ()
#9  0x00007fdfd5b4475a in object_set_property () at /lib64/libgobject-2.0.so.0
#10 0x00007fdfd5b47697 in g_object_setv () at /lib64/libgobject-2.0.so.0
#11 0x00007fdfd5b478d1 in g_object_set_property () at /lib64/libgobject-2.0.so.0
#12 0x00007fdfd5bdb461 in gimp_config_sync () at /lib64/libgimpconfig-3.0.so.0
#13 0x0000563da488f781 in gimp_context_copy ()
#14 0x00007fdfd5bd8e64 in gimp_config_copy () at /lib64/libgimpconfig-3.0.so.0
#15 0x00007fdfd5bd8ff0 in gimp_config_iface_duplicate () at /lib64/libgimpconfig-3.0.so.0
#16 0x0000563da488f5b8 in gimp_context_duplicate ()
#17 0x0000563da48e153c in gimp_tool_preset_set_options ()
#18 0x00007fdfd5b4475a in object_set_property () at /lib64/libgobject-2.0.so.0
#19 0x00007fdfd5b47ac6 in g_object_set_valist () at /lib64/libgobject-2.0.so.0
#20 0x00007fdfd5b47f5d in g_object_set () at /lib64/libgobject-2.0.so.0
#21 0x0000563da4bc73d9 in gimp_device_info_save_tool ()
#22 0x0000563da4b56153 in gimp_devices_restore ()
#23 0x0000563da4aa9952 in gui_restore_after_callback ()
#24 0x00007fdfd5b3452a in g_closure_invoke () at /lib64/libgobject-2.0.so.0
#25 0x00007fdfd5b633a5 in signal_emit_unlocked_R.isra.0 () at /lib64/libgobject-2.0.so.0
#26 0x00007fdfd5b53d59 in signal_emit_valist_unlocked () at /lib64/libgobject-2.0.so.0
#27 0x00007fdfd5b53f91 in g_signal_emit_valist () at /lib64/libgobject-2.0.so.0
#28 0x00007fdfd5b54053 in g_signal_emit () at /lib64/libgobject-2.0.so.0
#29 0x0000563da488a09d in gimp_restore ()
#30 0x0000563da4a6fdfe in app_activate_callback ()
#31 0x00007fdfd5b3452a in g_closure_invoke () at /lib64/libgobject-2.0.so.0
#32 0x00007fdfd5b62fec in signal_emit_unlocked_R.isra.0 () at /lib64/libgobject-2.0.so.0
#33 0x00007fdfd5b53d59 in signal_emit_valist_unlocked () at /lib64/libgobject-2.0.so.0
#34 0x00007fdfd5b53f91 in g_signal_emit_valist () at /lib64/libgobject-2.0.so.0
#35 0x00007fdfd5b54053 in g_signal_emit () at /lib64/libgobject-2.0.so.0
#36 0x00007fdfd5242778 in g_application_real_local_command_line () at /lib64/libgio-2.0.so.0
#37 0x00007fdfd5242923 in g_application_run () at /lib64/libgio-2.0.so.0
#38 0x0000563da4a6eac6 in app_run ()
#39 0x0000563da4883737 in main ()
[Inferior 1 (process 585781) detached]

```
> GIMP-WARNING: gimp_babl_format_get_with_alpha: unsupported format "HSVA float".

Stack trace:
```

# Stack traces obtained from PID 585781 - Thread 585781 #

[New LWP 585832]
[New LWP 585833]
[New LWP 585835]
[New LWP 585872]
[New LWP 585873]
[New LWP 585874]
[New LWP 585916]
[New LWP 585954]

This GDB supports auto-downloading debuginfo from the following URLs:
  <https://debuginfod.fedoraproject.org/>
Enable debuginfod for this session? (y or [n]) [answered N; input not from terminal]
Debuginfod has been disabled.
To make this setting permanent, add 'set debuginfod enabled off' to .gdbinit.
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
0x00007fdfd41d540a in read () from /lib64/libc.so.6
  Id   Target Id                                           Frame 
* 1    Thread 0x7fdfd2425fc0 (LWP 585781) "gimp-2.99"      0x00007fdfd41d540a in read () from /lib64/libc.so.6
  2    Thread 0x7fdfc46006c0 (LWP 585832) "pool-spawner"   0x00007fdfd41e085d in syscall () from /lib64/libc.so.6
  3    Thread 0x7fdfbbc006c0 (LWP 585833) "gmain"          0x00007fdfd41d4e3d in poll () from /lib64/libc.so.6
  4    Thread 0x7fdfc3c006c0 (LWP 585835) "gdbus"          0x00007fdfd41d4e3d in poll () from /lib64/libc.so.6
  5    Thread 0x7fdfc32006c0 (LWP 585872) "worker"         0x00007fdfd41e085d in syscall () from /lib64/libc.so.6
  6    Thread 0x7fdfc28006c0 (LWP 585873) "worker"         0x00007fdfd41e085d in syscall () from /lib64/libc.so.6
  7    Thread 0x7fdfc1e006c0 (LWP 585874) "worker"         0x00007fdfd41e085d in syscall () from /lib64/libc.so.6
  8    Thread 0x7fdfb34006c0 (LWP 585916) "async"          0x00007fdfd41e085d in syscall () from /lib64/libc.so.6
  9    Thread 0x7fdfb2a006c0 (LWP 585954) "pool-gimp-2.99" 0x00007fdfd41e085d in syscall () from /lib64/libc.so.6
#0  0x00007fdfd41d540a in read () at /lib64/libc.so.6
#1  0x00007fdfd5c223b4 in gimp_stack_trace_print () at /lib64/libgimpbase-3.0.so.0
#2  0x0000563da4ab1f1e in gui_message ()
#3  0x0000563da48ebb5a in gimp_show_message ()
#4  0x0000563da4a6eea2 in gimp_message_log_func ()
#5  0x00007fdfd55e0180 in g_logv () at /lib64/libglib-2.0.so.0
#6  0x00007fdfd55e0463 in g_log () at /lib64/libglib-2.0.so.0
#7  0x00007fdfd5bf5250 in gimp_color_set_alpha () at /lib64/libgimpcolor-3.0.so.0
#8  0x0000563da4890a71 in gimp_context_real_set_foreground ()
#9  0x00007fdfd5b4475a in object_set_property () at /lib64/libgobject-2.0.so.0
#10 0x00007fdfd5b47697 in g_object_setv () at /lib64/libgobject-2.0.so.0
#11 0x00007fdfd5b478d1 in g_object_set_property () at /lib64/libgobject-2.0.so.0
#12 0x00007fdfd5bdb461 in gimp_config_sync () at /lib64/libgimpconfig-3.0.so.0
#13 0x0000563da488f781 in gimp_context_copy ()
#14 0x00007fdfd5bd8e64 in gimp_config_copy () at /lib64/libgimpconfig-3.0.so.0
#15 0x00007fdfd5bd8ff0 in gimp_config_iface_duplicate () at /lib64/libgimpconfig-3.0.so.0
#16 0x0000563da488f5b8 in gimp_context_duplicate ()
#17 0x0000563da48e153c in gimp_tool_preset_set_options ()
#18 0x00007fdfd5b4475a in object_set_property () at /lib64/libgobject-2.0.so.0
#19 0x00007fdfd5b47ac6 in g_object_set_valist () at /lib64/libgobject-2.0.so.0
#20 0x00007fdfd5b47f5d in g_object_set () at /lib64/libgobject-2.0.so.0
#21 0x0000563da4b5615b in gimp_devices_restore ()
#22 0x0000563da4aa9952 in gui_restore_after_callback ()
#23 0x00007fdfd5b3452a in g_closure_invoke () at /lib64/libgobject-2.0.so.0
#24 0x00007fdfd5b633a5 in signal_emit_unlocked_R.isra.0 () at /lib64/libgobject-2.0.so.0
#25 0x00007fdfd5b53d59 in signal_emit_valist_unlocked () at /lib64/libgobject-2.0.so.0
#26 0x00007fdfd5b53f91 in g_signal_emit_valist () at /lib64/libgobject-2.0.so.0
#27 0x00007fdfd5b54053 in g_signal_emit () at /lib64/libgobject-2.0.so.0
#28 0x0000563da488a09d in gimp_restore ()
#29 0x0000563da4a6fdfe in app_activate_callback ()
#30 0x00007fdfd5b3452a in g_closure_invoke () at /lib64/libgobject-2.0.so.0
#31 0x00007fdfd5b62fec in signal_emit_unlocked_R.isra.0 () at /lib64/libgobject-2.0.so.0
#32 0x00007fdfd5b53d59 in signal_emit_valist_unlocked () at /lib64/libgobject-2.0.so.0
#33 0x00007fdfd5b53f91 in g_signal_emit_valist () at /lib64/libgobject-2.0.so.0
#34 0x00007fdfd5b54053 in g_signal_emit () at /lib64/libgobject-2.0.so.0
#35 0x00007fdfd5242778 in g_application_real_local_command_line () at /lib64/libgio-2.0.so.0
#36 0x00007fdfd5242923 in g_application_run () at /lib64/libgio-2.0.so.0
#37 0x0000563da4a6eac6 in app_run ()
#38 0x0000563da4883737 in main ()
[Inferior 1 (process 585781) detached]

```
> GIMP-WARNING: gimp_babl_format_get_with_alpha: unsupported format "HSVA float".

Stack trace:
```

# Stack traces obtained from PID 585781 - Thread 585781 #

[New LWP 585832]
[New LWP 585833]
[New LWP 585835]
[New LWP 585872]
[New LWP 585873]
[New LWP 585874]
[New LWP 585916]
[New LWP 585954]

This GDB supports auto-downloading debuginfo from the following URLs:
  <https://debuginfod.fedoraproject.org/>
Enable debuginfod for this session? (y or [n]) [answered N; input not from terminal]
Debuginfod has been disabled.
To make this setting permanent, add 'set debuginfod enabled off' to .gdbinit.
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
0x00007fdfd41d540a in read () from /lib64/libc.so.6
  Id   Target Id                                           Frame 
* 1    Thread 0x7fdfd2425fc0 (LWP 585781) "gimp-2.99"      0x00007fdfd41d540a in read () from /lib64/libc.so.6
  2    Thread 0x7fdfc46006c0 (LWP 585832) "pool-spawner"   0x00007fdfd41e085d in syscall () from /lib64/libc.so.6
  3    Thread 0x7fdfbbc006c0 (LWP 585833) "gmain"          0x00007fdfd41d4e3d in poll () from /lib64/libc.so.6
  4    Thread 0x7fdfc3c006c0 (LWP 585835) "gdbus"          0x00007fdfd41d4e3d in poll () from /lib64/libc.so.6
  5    Thread 0x7fdfc32006c0 (LWP 585872) "worker"         0x00007fdfd41e085d in syscall () from /lib64/libc.so.6
  6    Thread 0x7fdfc28006c0 (LWP 585873) "worker"         0x00007fdfd41e085d in syscall () from /lib64/libc.so.6
  7    Thread 0x7fdfc1e006c0 (LWP 585874) "worker"         0x00007fdfd41e085d in syscall () from /lib64/libc.so.6
  8    Thread 0x7fdfb34006c0 (LWP 585916) "async"          0x00007fdfd41e085d in syscall () from /lib64/libc.so.6
  9    Thread 0x7fdfb2a006c0 (LWP 585954) "pool-gimp-2.99" 0x00007fdfd41e085d in syscall () from /lib64/libc.so.6
#0  0x00007fdfd41d540a in read () at /lib64/libc.so.6
#1  0x00007fdfd5c223b4 in gimp_stack_trace_print () at /lib64/libgimpbase-3.0.so.0
#2  0x0000563da4ab1f1e in gui_message ()
#3  0x0000563da48ebb5a in gimp_show_message ()
#4  0x0000563da4a6eea2 in gimp_message_log_func ()
#5  0x00007fdfd55e0180 in g_logv () at /lib64/libglib-2.0.so.0
#6  0x00007fdfd55e0463 in g_log () at /lib64/libglib-2.0.so.0
#7  0x00007fdfd5bf5250 in gimp_color_set_alpha () at /lib64/libgimpcolor-3.0.so.0
#8  0x0000563da4890a71 in gimp_context_real_set_foreground ()
#9  0x00007fdfd5b4475a in object_set_property () at /lib64/libgobject-2.0.so.0
#10 0x00007fdfd5b47697 in g_object_setv () at /lib64/libgobject-2.0.so.0
#11 0x00007fdfd5b478d1 in g_object_set_property () at /lib64/libgobject-2.0.so.0
#12 0x00007fdfd5bdb461 in gimp_config_sync () at /lib64/libgimpconfig-3.0.so.0
#13 0x0000563da488f781 in gimp_context_copy ()
#14 0x00007fdfd5bd8e64 in gimp_config_copy () at /lib64/libgimpconfig-3.0.so.0
#15 0x00007fdfd5bd8ff0 in gimp_config_iface_duplicate () at /lib64/libgimpconfig-3.0.so.0
#16 0x0000563da488f5b8 in gimp_context_duplicate ()
#17 0x0000563da48e153c in gimp_tool_preset_set_options ()
#18 0x00007fdfd5b4475a in object_set_property () at /lib64/libgobject-2.0.so.0
#19 0x00007fdfd5b47ac6 in g_object_set_valist () at /lib64/libgobject-2.0.so.0
#20 0x00007fdfd5b47f5d in g_object_set () at /lib64/libgobject-2.0.so.0
#21 0x0000563da4bc73d9 in gimp_device_info_save_tool ()
#22 0x0000563da4b56153 in gimp_devices_restore ()
#23 0x0000563da4aa9952 in gui_restore_after_callback ()
#24 0x00007fdfd5b3452a in g_closure_invoke () at /lib64/libgobject-2.0.so.0
#25 0x00007fdfd5b633a5 in signal_emit_unlocked_R.isra.0 () at /lib64/libgobject-2.0.so.0
#26 0x00007fdfd5b53d59 in signal_emit_valist_unlocked () at /lib64/libgobject-2.0.so.0
#27 0x00007fdfd5b53f91 in g_signal_emit_valist () at /lib64/libgobject-2.0.so.0
#28 0x00007fdfd5b54053 in g_signal_emit () at /lib64/libgobject-2.0.so.0
#29 0x0000563da488a09d in gimp_restore ()
#30 0x0000563da4a6fdfe in app_activate_callback ()
#31 0x00007fdfd5b3452a in g_closure_invoke () at /lib64/libgobject-2.0.so.0
#32 0x00007fdfd5b62fec in signal_emit_unlocked_R.isra.0 () at /lib64/libgobject-2.0.so.0
#33 0x00007fdfd5b53d59 in signal_emit_valist_unlocked () at /lib64/libgobject-2.0.so.0
#34 0x00007fdfd5b53f91 in g_signal_emit_valist () at /lib64/libgobject-2.0.so.0
#35 0x00007fdfd5b54053 in g_signal_emit () at /lib64/libgobject-2.0.so.0
#36 0x00007fdfd5242778 in g_application_real_local_command_line () at /lib64/libgio-2.0.so.0
#37 0x00007fdfd5242923 in g_application_run () at /lib64/libgio-2.0.so.0
#38 0x0000563da4a6eac6 in app_run ()
#39 0x0000563da4883737 in main ()
[Inferior 1 (process 585781) detached]

```
> GIMP-WARNING: gimp_babl_format_get_with_alpha: unsupported format "HSVA float".

> GIMP-WARNING: gimp_babl_format_get_with_alpha: unsupported format "HSVA float".

> GIMP-WARNING: gimp_babl_format_get_with_alpha: unsupported format "HSVA float".

> GIMP-WARNING: gimp_babl_format_get_with_alpha: unsupported format "HSVA float".

> GIMP-WARNING: gimp_babl_format_get_with_alpha: unsupported format "HSVA float".

> GIMP-WARNING: gimp_babl_format_get_with_alpha: unsupported format "HSVA float".

> GIMP-WARNING: gimp_babl_format_get_with_alpha: unsupported format "HSVA float".

**Comment by Bgs4269** [comment]
Closing the bug window, GIMP keeps running and as far as I can tell it works, but the message pops up every couple of clicks.
